Repository LikeLion-at-DGU/2025-simba-3-leader200nam, pull requests merged in 2025-06, with the labels that each got.

#2 feat: Add homepage
  main/templates/main/mainpage.html
  project/static/css/base/font.css
  project/static/css/base/style.css
  project/static/css/page/mainpage.css
  project/static/images/ako1.svg
  project/static/js/page/mainpage.js
Labels: feat

#6 feat: 로그인, 회원가입 디자인 구현
  main/templates/signin/signin.html
  main/templates/signup/signup.html
  main/views.py
  project/static/css/accounts/signin/signin.css
  project/static/css/accounts/signup/signup.css
  project/static/css/page/mainpage.css
  project/static/images/back-icon.svg
  project/static/images/check-icon.svg
  project/static/images/delete-icon.svg
  project/static/images/error-icon.svg
  project/static/images/logo-img.svg
  project/static/images/toggle-off-icon.svg
  project/static/images/toggle-on-icon.svg
  project/static/js/accounts/signin.js
  project/static/js/accounts/signup.js
  project/urls.py
Labels: feat, 지연

#11 Feature/login
  main/templates/intro/introInputPage.html
  main/templates/main/registeration.html
  main/views.py
  project/static/css/accounts/signin/signin.css
  project/static/css/accounts/signup/signup.css
  project/static/css/page/introInputPage.css
  project/static/css/page/registeration.css
  project/static/images/Vector.svg
  project/static/images/image.svg
  project/static/js/accounts/signup.js
  project/static/js/page/introInputPage.js
  project/static/js/page/registeration.js
  project/urls.py
Labels: feat, 지연

#29 feat: 퀘스트 조회 및 퀘스트 인증 구현
  feed/views.py
  main/templates/main/mainpage.html
  main/templates/main/profileModification.html
  main/templates/main/registeration.html
  main/views.py
  project/static/css/common/popup.css
  project/static/css/page/mainpage.css
  project/static/css/page/registeration.css
  project/static/images/profile-default.svg
  project/static/images/success.svg
  project/static/js/base/popup.js
  project/static/js/page/mainpage.js
  project/static/js/page/registeration.js
  project/templates/common/_navbar.html
Labels: feat, 지연

#30 fix: 비공개/공개 데이터 처리
  main/templates/main/registeration.html
  main/views.py
  project/static/js/page/registeration.js
Labels: fix, 지연

#47 주석, 리팩터링(중복, 불필요 코드 삭제)
  accounts/tests.py
  feed/migrations/0002_remove_feedcommentreply_feed_comment_and_more.py
  feed/models.py
  feed/tests.py
  feed/urls.py
  feed/views.py
  friends/migrations/0001_initial.py
  friends/migrations/0002_friend_memo.py
  friends/migrations/0002_friend_status.py
  friends/migrations/0003_alter_friendcode_unique_together.py
  friends/models.py
  friends/tests.py
  friends/urls.py
  friends/views.py
  main/tests.py
  quest/migrations/0001_initial.py
  quest/migrations/0002_add_initial_quest_data.py
  quest/migrations/0003_alter_quest_id.py
  quest/models.py
  quest/tests.py
  quest/urls.py
  quest/views.py
Labels: 현노, refactor

#52 Fix: 게시글 신고 기능 오류 해결
  feed/urls.py
  project/static/js/page/feedpage.js
  project/static/js/page/friendpage.js
Labels: fix, 지연

#53 Feature/loginCommits on Jun 25, 2025 Fix: 회원가입 오류 메세지 수정
  accounts/templates/signup.html
Labels: fix, 지연

#55 Fix: 피드 오류 수정
  feed/views.py
  project/static/js/page/feedpage.js
Labels: fix, 지연

#56 Feat: README.md 추가
  .gitignore
  README.md
  db.sqlite3
Labels: feat, 지연
